"""Build the tune set from the 360VOS training split.

    python tools/prepare_tune_set.py split    --info <360vots-info.csv> --train-root <train>
    python tools/prepare_tune_set.py labels   --train-root <train> --label-root <dir>
    python tools/prepare_tune_set.py validate --info <csv> --train-root <train> --vot-root <test>

``split`` writes the exclusion list and the tune list under ``configs/splits``.
``labels`` fits 360VOT-style labels from the masks of the tune sequences.
``validate`` compares such fitted labels with official 360VOT labels on clips that
have both.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

from track360.core.errors import Track360Error
from track360.datasets.mask_labels import labelFromMask, readTargetMask, writeSequenceLabels
from track360.datasets.tune_split import (
    excludedTrainClips,
    leakFreePool,
    readSequenceFile,
    selectTuneSet,
)
from track360.datasets.vot360 import Vot360Dataset
from track360.datasets.vots_info import loadVotsInfo

SPLIT_DIRECTORY = Path(__file__).resolve().parents[1] / "configs" / "splits"
EXCLUDED_FILE = SPLIT_DIRECTORY / "360vos_train_excluded.csv"
TUNE_FILE = SPLIT_DIRECTORY / "360vos_tune.txt"
TUNE_SIZE = 25
TUNE_MAX_FRAMES = 1000


def buildParser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    commands = parser.add_subparsers(dest="command", required=True)
    split = commands.add_parser("split", help="write the exclusion list and the tune list")
    split.add_argument("--info", required=True)
    split.add_argument("--train-root", required=True)
    labels = commands.add_parser("labels", help="fit labels from masks for the tune sequences")
    labels.add_argument("--train-root", required=True)
    labels.add_argument("--label-root", required=True)
    labels.add_argument("--sequence-file", type=Path, default=TUNE_FILE)
    validate = commands.add_parser("validate", help="compare fitted labels with official ones")
    validate.add_argument("--info", required=True)
    validate.add_argument("--train-root", required=True)
    validate.add_argument("--vot-root", required=True)
    validate.add_argument("--frames-per-sequence", type=int, default=12)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = buildParser().parse_args(argv)
    try:
        if args.command == "split":
            return _split(args)
        if args.command == "labels":
            return _labels(args)
        return _validate(args)
    except Track360Error as error:
        print(f"{type(error).__name__}: {error}", file=sys.stderr)
        return 2


def _split(args: argparse.Namespace) -> int:
    info = loadVotsInfo(args.info)
    dataset = Vot360Dataset(args.train_root)
    excluded = excludedTrainClips(info)
    pool = leakFreePool(info)
    frameCounts = {}
    for clip in pool:
        sequence = dataset.sequence(clip.vosId)
        frameCounts[clip.vosId] = sequence.frameCount
        sequence.close()
    tune = selectTuneSet(pool, frameCounts, size=TUNE_SIZE, maxFrames=TUNE_MAX_FRAMES)

    SPLIT_DIRECTORY.mkdir(parents=True, exist_ok=True)
    rows = ["vos_train_id,reason,detail"]
    rows += [f"{item.vosId},{item.reason},{item.detail}" for item in excluded]
    EXCLUDED_FILE.write_text("\n".join(rows) + "\n", encoding="utf-8", newline="\n")
    header = [
        "# Tune set: 360VOS training sequences used for every tuning decision.",
        "# Generated by tools/prepare_tune_set.py split; do not edit by hand.",
        f"# Pool: {len(pool)} training sequences left after 360vos_train_excluded.csv.",
        f"# Selection: greedy attribute coverage, {TUNE_SIZE} sequences of at most "
        f"{TUNE_MAX_FRAMES} frames.",
        "# <id>  # frames, target, attributes",
    ]
    body = [
        f"{clip.vosId}  # {frameCounts[clip.vosId]}, {clip.target}, "
        f"{' '.join(name for name in info.attributeNames if name in clip.attributes)}"
        for clip in tune
    ]
    TUNE_FILE.write_text("\n".join(header + body) + "\n", encoding="utf-8", newline="\n")

    reasons: dict[str, int] = {}
    for item in excluded:
        reasons[item.reason] = reasons.get(item.reason, 0) + 1
    print(f"training sequences: {len(info.vosClips('train'))}")
    for reason, count in reasons.items():
        print(f"  excluded, {reason}: {count}")
    print(f"  leak-free pool: {len(pool)}")
    print(f"tune set: {len(tune)} sequences, {sum(frameCounts[c.vosId] for c in tune)} frames")
    coverage = {
        name: sum(1 for clip in tune if name in clip.attributes) for name in info.attributeNames
    }
    print("attribute coverage: " + " ".join(f"{name}={count}" for name, count in coverage.items()))
    return 0


def _labels(args: argparse.Namespace) -> int:
    dataset = Vot360Dataset(args.train_root)
    for position, name in enumerate(names := readSequenceFile(args.sequence_file), start=1):
        target = Path(args.label_root) / name / "label.json"
        if target.is_file():
            print(f"[{position}/{len(names)}] {name}: exists")
            continue
        sequence = dataset.sequence(name)
        writeSequenceLabels(sequence, args.label_root)
        print(f"[{position}/{len(names)}] {name}: {sequence.frameCount} frames")
        sequence.close()
    return 0


def _validate(args: argparse.Namespace) -> int:
    info = loadVotsInfo(args.info)
    train = Vot360Dataset(args.train_root)
    official = Vot360Dataset(args.vot_root)
    ious: list[float] = []
    centers: list[float] = []
    fovs: list[tuple[float, float]] = []
    presenceMismatch = sequences = 0
    for clip in info.vosClips("train"):
        if clip.votId is None or clip.multipleTargets:
            continue
        masked = train.sequence(clip.vosId)
        labelled = official.sequence(clip.votId)
        # Some clips were re-cut between the two benchmarks; only equal lengths align.
        if masked.frameCount == labelled.frameCount:
            sequences += 1
            width = labelled.frameSize[0]
            boxes, boxPresent = labelled.groundTruth("bbox")
            bfovs, _ = labelled.groundTruth("bfov")
            picks = np.linspace(0, masked.frameCount - 1, args.frames_per_sequence).astype(int)
            for index in picks:
                label = labelFromMask(readTargetMask(masked, int(index)))
                present = label["bbox"]["w"] > 0
                if present != bool(boxPresent[index]):
                    presenceMismatch += 1
                elif present:
                    box = label["bbox"]
                    fitted = (
                        box["cx"] - box["w"] / 2.0,
                        box["cy"] - box["h"] / 2.0,
                        box["w"],
                        box["h"],
                    )
                    ious.append(_circularIou(fitted, boxes[index], width))
                    bfov = label["bfov"]
                    centers.append(_angleDeg(bfov["clon"], bfov["clat"], *bfovs[index][:2]))
                    fovs.append(
                        (
                            abs(bfov["fov_h"] - bfovs[index][2]),
                            abs(bfov["fov_v"] - bfovs[index][3]),
                        )
                    )
        masked.close()
        labelled.close()
    iou = np.asarray(ious)
    center = np.asarray(centers)
    fov = np.asarray(fovs)
    print(
        f"sequences compared: {sequences}; frames: {len(iou)}; "
        f"presence mismatches: {presenceMismatch}"
    )
    print(
        f"bbox IoU: median {np.median(iou):.4f}, 5th percentile {np.percentile(iou, 5):.4f}, "
        f"share above 0.9: {(iou > 0.9).mean():.3f}"
    )
    print(
        f"bfov center difference (deg): median {np.median(center):.3f}, "
        f"95th percentile {np.percentile(center, 95):.3f}"
    )
    medianH, medianV = np.median(fov, axis=0)
    highH, highV = np.percentile(fov, 95, axis=0)
    print(
        f"bfov size difference (deg, h / v): median {medianH:.3f} / {medianV:.3f}, "
        f"95th percentile {highH:.2f} / {highV:.2f}"
    )
    return 0


def _circularIou(first: tuple[float, ...], second: np.ndarray, width: int) -> float:
    best = 0.0
    for shift in (-width, 0, width):
        left = max(first[0], second[0] + shift)
        right = min(first[0] + first[2], second[0] + shift + second[2])
        top = max(first[1], second[1])
        bottom = min(first[1] + first[3], second[1] + second[3])
        overlap = max(0.0, right - left) * max(0.0, bottom - top)
        best = max(best, overlap / (first[2] * first[3] + second[2] * second[3] - overlap))
    return best


def _angleDeg(lonA: float, latA: float, lonB: float, latB: float) -> float:
    def direction(lon: float, lat: float) -> np.ndarray:
        lon, lat = np.radians(lon), np.radians(lat)
        return np.array([np.cos(lat) * np.sin(lon), np.sin(lat), np.cos(lat) * np.cos(lon)])

    cosine = np.clip(direction(lonA, latA) @ direction(lonB, latB), -1.0, 1.0)
    return float(np.degrees(np.arccos(cosine)))


if __name__ == "__main__":
    raise SystemExit(main())
